apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: message-board
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: message-board
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: pgsql-1
  source:
    git:
      url: https://github.com/natarajmb/message-board.git
      ref:
        branch: main